name: grphin
channels:
  - conda-forge
  - defaults
  - https://conda.anaconda.org/gurobi
dependencies:
  - brotli=1.1.0=h00291cd_2
  - brotli-bin=1.1.0=h00291cd_2
  - bzip2=1.0.8=hfdf4475_7
  - ca-certificates=2024.12.14=h8857fd0_0
  - contourpy=1.3.1=py313ha0b1807_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - fonttools=4.55.3=py313h717bdf5_0
  - freetype=2.12.1=h60636b9_2
  - kiwisolver=1.4.7=py313h0c4e38b_0
  - lcms2=2.16=ha2f27b4_0
  - lerc=4.0.0=hb486fe8_0
  - libblas=3.9.0=26_osx64_openblas
  - libbrotlicommon=1.1.0=h00291cd_2
  - libbrotlidec=1.1.0=h00291cd_2
  - libbrotlienc=1.1.0=h00291cd_2
  - libcblas=3.9.0=26_osx64_openblas
  - libcxx=19.1.6=hf95d169_1
  - libdeflate=1.23=he65b83e_0
  - libexpat=2.6.4=h240833e_0
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libjpeg-turbo=3.0.0=h0dc2134_1
  - liblapack=3.9.0=26_osx64_openblas
  - liblzma=5.6.3=hd471939_1
  - libmpdec=4.0.0=hfdf4475_0
  - libopenblas=0.3.28=openmp_hbf64a52_1
  - libpng=1.6.44=h4b8f8c9_0
  - libsqlite=3.47.2=hdb6dae5_0
  - libtiff=4.7.0=hb77a491_3
  - libwebp-base=1.4.0=h10d778d_0
  - libxcb=1.17.0=hf1f96e2_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=19.1.6=ha54dae1_0
  - matplotlib-base=3.10.0=py313he981572_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=hf036a51_1
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.0=py313h6ae94ac_0
  - openjpeg=2.5.3=h7fd6d84_0
  - openssl=3.4.0=hd471939_0
  - packaging=24.2=pyhd8ed1ab_2
  - pillow=11.0.0=py313h4d44d4f_0
  - pip=24.3.1=pyh145f28c_2
  - pthread-stubs=0.4=h00291cd_1002
  - pyparsing=3.2.0=pyhd8ed1ab_2
  - python=3.13.1=h2334245_102_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.13=5_cp313
  - qhull=2020.2=h3c5361c_5
  - readline=8.2=h9e318b2_1
  - scipy=1.14.1=py313hd641537_2
  - six=1.17.0=pyhd8ed1ab_0
  - tk=8.6.13=h1abcd95_1
  - tzdata=2024b=hc8b5060_0
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - zstd=1.5.6=h915ae27_0